# Generated by Django 2.2.10 on 2020-06-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterModelOptions(
            name='scopearticle',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статей'},
        ),
        migrations.AlterField(
            model_name='scope',
            name='article',
            field=models.ManyToManyField(related_name='scope', through='articles.ScopeArticle', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='scopearticle',
            name='is_main',
            field=models.BooleanField(verbose_name='Основной'),
        ),
    ]
