# Generated by Django 2.2.10 on 2020-06-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200620_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='article',
            field=models.ManyToManyField(related_name='scopes', through='articles.ScopeArticle', to='articles.Article'),
        ),
    ]
