# Generated by Django 2.2.10 on 2020-06-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200622_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopearticle',
            options={'ordering': ['is_main'], 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статей'},
        ),
    ]
