# Generated by Django 2.2.10 on 2020-06-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200622_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-published_at',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterModelOptions(
            name='scopearticle',
            options={'ordering': ('-is_main', 'scope__topic'), 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статей'},
        ),
    ]
